# Generated by Django 5.0.6 on 2024-10-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=500)),
                ('imageurl', models.CharField(max_length=2000)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
